"""New Migration

Revision ID: 9314dc57b323
Revises: 2975e16a4851
Create Date: 2021-07-19 12:59:09.543207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9314dc57b323'
down_revision = '2975e16a4851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
